import animations from './animations';
import audio from './audio';
import canvasLines from './canvasLines';
import hello from './hello';
import lazyLoad from './lazyLoad';
import miniPlayer from './miniPlayer';
import mobileMenu from './mobileMenu';
import popup from './popup';
import video from './video';